version: '3'
services:
  iverilog:
    container_name: iverilog
    build:
      context: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    # command: /app/simulate.sh my_design.sv my_testbench.sv -w
    